# Jekyll Stuff:
layouts_dir:  ./_jekyll/_layouts
includes_dir:  ./_jekyll/_includes

exclude:
  - README.markdown
  - LICENSE
  - Makefile
  - assets/img/Makefile
  - matplotlibrc
  - site-markdown.tpl
  - deploy.sh
  - jsbsim.tar.gz
  - jsbsim
encoding: "utf-8"
markdown: kramdown
kramdown:
  toc_levels: "2,3"
highlighter: rouge
excerpt_separator: "\n\n\n\n"
sass:
    style: compressed
permalink: :categories/:year/:title/


# Site definitions:
site_title: "Open Source Aerospace Computing"
site_subtitle: "Modeling **rockets** with open source tools and methods"


