# Jekyll Stuff:
layouts_dir:  ./_jekyll/_layouts
exclude:
  - README.markdown
  - Makefile
  - assets/img/Makefile
  - matplotlibrc
  - site-markdown.tpl
  - deploy.sh
encoding: "utf-8"
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n\n\n"
sass:
    style: compressed
permalink: :categories/:year/:title/

# Site definitions:
site_title: "Open Source Aerospace Computing"
site_subtitle: "Modeling **rockets** with open source tools and methods"

nav:
  - title: Home
    url: /
    name: home
  - title: News
    url: /news/
    name: news
  - title: "JSBSim: NASA Test Cases"
    url: /jsbsim-nasa-test-cases/
    name: jsbsimtest
