# Jekyll Stuff:
layouts_dir:  ./_jekyll/_layouts
exclude:
  - README.markdown
  - Makefile
  - assets/img/Makefile
encoding: "utf-8"
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n\n\n"
sass:
    style: compressed
permalink: news/:year/:title/

# Site definitions:
site_title: "Open Source Aerospace Computing"
site_subtitle: "Modeling **rockets** with open source tools and methods"
